language: python
python:
  - 3.8
services: 
  - mongodb
before_install:
  - python --version
  - pip install -U pip
  - pip install -r requirements.txt
before_script:
  - sleep 15
  - mongo mydb_test['my_gfg_collection '] --eval 'db.insert_one({"name":"Mr.Geek","eid":24,"location":"delhi"});'
script: python app.py
notifications:
  email:
    recipients:
      - vpokhapkin@yandex.ru
    on_success: never
    on_failure: change
